### ISSUE TITLE
Question [custom features!]

### ISSUE THREAD

**Issue by HamidHadipour** [ChatterjeeAyan/AI-Bind#1]
Hi,
I am just wondering if you can help me figure out how can I use my own features for chemical molecules and proteins separately.

Thank you
@ChatterjeeAyan 
@rsfwalters

**Comment by ChatterjeeAyan** [comment]
Hi,

Please check the file: AIBind/AIBind.py
You can modify the embedding functions for any of the AI-Bind architectures. For example, you can modify the VecNet Functions get_mol2vec_embeddings and get_protvec_embeddings with your custom embeddings functions. Make sure that the embedding dimensions are compatible with the decoder vecnet_2048_2048_concat_512_512.

Hope this information was helpful.

Thanks,
Ayan
