### ISSUE TITLE
Installing via docker stops (seems due to 404 error). Dead links in wget

### ISSUE THREAD

**Issue by P-Wengert** [ChatterjeeAyan/AI-Bind#2]
Hello guys,

I tried to install this tool using the docker file, as per the instructions, but when I try, the error shown in the attached file appears.

I checked the first four of the wget links in the file, and all of them say the file was deleted, so the docker file is trying to wget dead links.

[Docker_error.txt](https://github.com/ChatterjeeAyan/AI-Bind/files/11211799/Docker_error.txt)

**Comment by ChatterjeeAyan** [comment]
Hi Peter,

Can you try using this docker image: https://hub.docker.com/r/omairs/foodome2?

Thanks,
Ayan
