### ISSUE TITLE
pip installing requirements file leads to error

### ISSUE THREAD

**Issue by P-Wengert** [ChatterjeeAyan/AI-Bind#3]
Hello guys,

I tried pip installing the requirements file, but I'm getting an error because the specified version of bazel seems to not exist:

(base) pwengert@Peters-Macbook-Pro AI-Bind-main % pip install -r requirements.txt                                 
...
ERROR: Could not find a version that satisfies the requirement bazel==0.0.0.20200723 (from versions: none)
ERROR: No matching distribution found for bazel==0.0.0.20200723

Do you know where I could get this file?

Best,
Peter

**Comment by P-Wengert** [comment]
There are actually several other errors which come up also, which I have documented in the attached txt file.

I think that the xgboost and tables ones are on me to fix though. 

[Requirements_Errors.txt](https://github.com/ChatterjeeAyan/AI-Bind/files/11212192/Requirements_Errors.txt)

**Comment by ChatterjeeAyan** [comment]
Hi Peter,

The packages for which there's no matching distribution available, you can skip installing most of them (e.g., bazel, dataclasses, mkl-fft etc.). AI-Bind should run fine without them. However, some of them are required for development purposes. 

You do need tensorflow-gpu==1.12.0. Check the CUDA and other requirements here: https://www.tensorflow.org/install/pip. I have also summarized the CUDA and GPU setting I used in the README file. 

Thanks,
Ayan

**Comment by ChatterjeeAyan** [comment]
Hi Peter,

Can you try the attached requirements file?

Thanks,
Ayan

[requirements.txt](https://github.com/ChatterjeeAyan/AI-Bind/files/11213767/requirements.txt)

**Comment by P-Wengert** [comment]
This new requirements file worked!

Thank you so much!
