### ISSUE TITLE
Difficulty running notebook

### ISSUE THREAD

**Issue by P-Wengert** [ChatterjeeAyan/AI-Bind#4]
Hello again,

I hope you are doing well.

I've created a csv file with the InChiKey, SMILE, and target_aa_code columns and I'm trying to run the VecNet-User-Frontend.ipynb notebook, but I'm coming across a bunch of issues.

There doesn't appear to be any /root/data/ directory, but loads of files in the script are supposedly stored there.
For example, under the pre-trained vecnet section, I get:

FileNotFoundError                         Traceback (most recent call last)
Cell In[15], line 1
----> 1 with open('/root/data/VecNet_unseen_nodes.pickle', 'rb') as file:
      2     vecnet_object = pkl.load(file) 

When I try to ignore that first section and get right to the "Prediction" portion of the notebook I end up getting the error "NameError: name 'vecnet_object' is not defined", presumably because I couldn't run the pre-trained vecnet section.
Is there a place where I can find the root/data directory and download all its contents?

As an aside, I'm new to using jupyter notebooks, so I'm not sure which parts of the notebook I have to run in order to get things to work. I obviously run the imports, but I'm not sure if I have to run things like the GPU settings subheader. This subheader throws an error because I'm using a macbook pro, which doesn't use nvidia. Therefore, nvidia-smi isn't a valid command on my machine. I skipped over this part because I just want to use the pre-trained model. Is this valid?

Best,
Peter

**Comment by ChatterjeeAyan** [comment]
Hi Peter,

Please check the documentation for 'Setting up AI-Bind and Predicting Protein-Ligand Binding (Guidelines for end users)' in the README file. You need to download the data files from https://zenodo.org/record/7226641 and store them in the '/root/data/' directory. We have shared the pre-trained VecNet models. You need to run all the cells in the frontend notebook for making predictions.

We use NVIDIA Tesla T4 GPU(s) + Python 3.6.6 + CUDA 9.0 for AI-Bind. If you want to run AI-Bind without GPU support, you need to retrain the models in https://github.com/ChatterjeeAyan/AI-Bind/blob/main/VecNet/VecNet-Unseen_Nodes.ipynb. I have used T4 GPUs throughout the whole project. You will need to make changes to the code for implementing a non-GPU version.

Hope this information helps.

Thanks,
Ayan

**Comment by P-Wengert** [comment]
Hi Ayan,

Thank you very much for all your help!

I'll try running the notebook on the university's GPU cluster.

Best,
Peter



> On Apr 14, 2023, at 3:35 PM, Ayan Chatterjee ***@***.***> wrote:
> 
> 
> Hi Peter,
> 
> Please check the documentation for 'Setting up AI-Bind and Predicting Protein-Ligand Binding (Guidelines for end users)' in the README file. You need to download the data files from https://zenodo.org/record/7226641 and store them in the '/root/data/' directory. We have shared the pre-trained VecNet models. You need to run all the cells in the frontend notebook for making predictions.
> 
> We use NVIDIA Tesla T4 GPU(s) + Python 3.6.6 + CUDA 9.0 for AI-Bind. If you want to run AI-Bind without GPU support, you need to retrain the models in. I have used T4 GPUs throughout the whole project. You will need to make changes to the code for implementing a non-GPU version.
> 
https://github.com/ChatterjeeAyan/AI-Bind/blob/main/VecNet/VecNet-Unseen_Nodes.ipynb￼
AI-Bind/VecNet-Unseen_Nodes.ipynb at main · ChatterjeeAyan/AI-Bind
github.com
