### ISSUE TITLE
Trouble loading model and running prediction

### ISSUE THREAD

**Issue by mslvlx** [ChatterjeeAyan/AI-Bind#5]
Hi, 

First of all, thanks for all your work. I was able to get everything up and running, however I am running into an issue when trying 
to predict. I looked at the Jupyter Notebook file and there are a couple of lines that throw errors in the Loading Pre-Trained Vec and Prediction section:

```
vecnet_object = AIBind.AIBind(interactions_location = '/root/data/Network_Derived_Negatives.csv',
                              interactions = None,
                              interaction_y_name = 'Y',

```
                              absolute_negatives_location = None,
                              absolute_negatives = None,

                              drugs_location = None,
                              drugs_dataframe = drugs,
                              drug_inchi_name = 'InChiKey',
                              drug_smile_name = 'SMILE',

                              targets_location = None,
                              targets_dataframe = targets, 
                              target_seq_name = 'target_aa_code',

                              mol2vec_location = None,
                              mol2vec_model = None,

                              protvec_location = None, 
                              protvec_model = None,

                              nodes_test = targets_test, 
                              nodes_validation = targets_validation, 

                              edges_test = edges_test, 
                              edges_validation = edges_validation, 

                              model_out_dir = '/root/data/',

                              debug = False)

This runs okay. However, I am confused by the next line, where you seem to be trying to allocate a pickle file to the previously created class instance? 

`with open('/root/data/VecNet_unseen_nodes.pickle', 'rb') as file:
    vecnet_object = pkl.load(file)`

Is this correct? Because this gives me the following error: 

`Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'AIBind.AIBind'; 'AIBind' is not a package' 

Also, I cannot follow the prediction example. 
You read in the test.csv with the following line: 

`nodes_df = pd.read_csv('Test.csv')`

However, nodes_df is then not used in the example: 

`unseen_nodes_example_5fold_average = vecnet_object.get_fold_averaged_prediction_results(model_name = None,
                                                                                     version_number = None,
                                                                                     model_paths = ['/root/data/VecNet_unseen_nodes.pickle'],
                                                                                     optimal_validation_model = None,
                                                                                     test_sets = [targets_test[1].dropna()],
                                                                                     get_drug_embed = True,
                                                                                     pred_drug_embeddings = nodes_df['InChiKey'],
                                                                                     get_target_embed = True,
                                                                                     pred_target_embeddings = nodes_df['target_aa_code'],
                                                                                     drug_filter_list = [],
                                                                                     target_filter_list = [],
                                                                                     return_dataframes = True )`

Can you please elaborate how to load the csv-data into the prediction? 

Thanks! 

Michael

`

**Comment by ChatterjeeAyan** [comment]
>> ModuleNotFoundError: No module named 'AIBind.AIBind'; 'AIBind' is not a package'
This one should work. If it doesn't, put the .py files inside the AIBind folder in the same directory as the prediction notebook and import them. 
>> Can you please elaborate how to load the csv-data into the prediction?
Can you change 'test_sets = [targets_test[1].dropna()]' to 'test_sets = [nodes_df.dropna()]' and give it a try?

**Comment by mslvlx** [comment]
Thanks for the quick reply! 
Moving the files into the /AIBind folder solved the first issue, thank you! 

The second one is also solved, the script runs now, thank you!
