### ISSUE TITLE
Pre-Trained Models for Multiple Target Classes

### ISSUE THREAD

**Issue by mmagithub** [ChatterjeeAyan/AI-Bind#6]
Hello,

I am impressed with the project and its scope. I am currently exploring options for leveraging pre-trained models, specifically ones that might have been trained on the entire BindingDB dataset, or similar. My goal is to make predictions for several target classes without the need for pretraining, similar to the functionality provided by DeepPurpose.

From what I have read, it seems that the existing models are predominantly focused on SARS-CoV-2. Could you please provide some insights or confirm whether there are other models available that cover a broader range of targets?

Thank you for your assistance.

Regards,

Marawan

**Comment by ChatterjeeAyan** [comment]
Hi Marawan,

Thanks for your interest in our work. AI-Bind ligand embeddings are derived from Mol2vec, which has a training corpus of 19M chemicals from PubChem. The protein embeddings are derived from Protvec, which has a training corpus of 500k proteins from SwissProt. Thus, the statement that 'it seems that the existing models are predominantly focused on SARS-CoV-2' is not true. We used SARS-CoV-2 proteins only for validation. AI-Bind applies to a wider range of proteins. Hope this answers your question.

Thanks,
Ayan
